### ISSUE TITLE
Documentation for visualization tools ?

### ISSUE THREAD

**Issue by nyue** [p-costa/CaNS#8]
Hi,

  There are some Python code which does visualization.

  I would be good to show an example usage in the README.md

  There is a xdmf generation fortran code. The example shell script does not say very much about how it can be used.

  I hope to ingest the computed data files *.out and do 3d visualization in applications like Paraview and Houdini

Cheers

**Comment by p-costa** [comment]
Hi,

Thanks for the suggestion. The *.out files are actually ascii files containing profiles or temporal histories of averaged quantities (you can plot it e.g. with gnuplot). The binary files *.bin are the ones that are used for visualization. Since they are written in raw binary format (double, little endian, Column major), they can be easily read with e.g. python, and plotted. The python script gives an example on how to.

> There is a xdmf generation fortran code. The example shell script does not say very much about how it can be used.
> 
> I hope to ingest the computed data files *.out and do 3d visualization in applications like Paraview and Houdini

The generated xdmf file also points to the *.bin files and can loaded with Paraview (and other equivalent tools I hope). The usage is explained in gen_xdmf.f90.

When I come back from holiday I'll try to make it more clear.

Cheers

**Comment by p-costa** [comment]
I added two explanatory readme.txt files.
